version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  Afterinstall:
    - location: script/install_httpd.sh
      timeout: 300
      runas: root
  Applicationstart:
    - location: script/start_httpd.sh
      timeout: 300
      runas: root